name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3

    # Setup for Node.js (common step)
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # Frontend
    - name: Install and build frontend
      run: |
        cd CS130/frontend
        npm ci
        npm run build --if-present
      shell: bash

    - name: Test frontend
      run: |
        cd CS130/frontend
        npm test
      shell: bash

    # Backend
    - name: Install and build backend
      run: |
        cd CS130/backend
        npm ci
        npm run build --if-present
      shell: bash

    - name: Test backend
      run: |
        cd CS130/backend
        npm test
      shell: bash
