name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        # Removed cache: 'npm' to disable automatic cache detection

    # Cache dependencies manually
    - name: Get npm cache directory
      id: npm-cache
      run: echo "::set-output name=dir::$(npm config get cache)"

    - name: Cache frontend dependencies
      uses: actions/cache@v2
      with:
        path: ${{ steps.npm-cache.outputs.dir }}
        key: ${{ runner.os }}-frontend-${{ hashFiles('CS130/frontend/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-frontend-

    - name: Cache backend dependencies
      uses: actions/cache@v2
      with:
        path: ${{ steps.npm-cache.outputs.dir }}
        key: ${{ runner.os }}-backend-${{ hashFiles('CS130/backend/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-backend-

    # Frontend
    - name: Install and build frontend
      run: |
        cd CS130/frontend
        npm ci
        npm run build --if-present
      shell: bash

    # Backend
    - name: Install and build backend
      run: |
        cd CS130/backend
        npm ci
        npm run build --if-present
      shell: bash

    - name: Test backend
      run: |
        cd CS130/backend
        npm test
      shell: bash
